# 실습 내용

- 데이터 : income_happy.csv
- LinearRegression 알고리즘을 사용한다.

# 1.환경 준비

- 기본 **라이브러리**와 대상 **데이터**를 가져와 이후 과정을 준비합니다.

In [1]:
# 라이브러리 불러오기
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings(action='ignore')
%config InlineBackend.figure_format = 'retina'

In [2]:
# 데이터 읽어오기
path = 'data/income_happy.csv'
df = pd.read_csv(path)

df

       income  happiness
0    3.862647   2.314489
1    4.979381   3.433490
2    4.923957   4.599373
3    3.214372   2.791114
4    7.196409   5.596398
..        ...        ...
493  5.249209   4.568705
494  3.471799   2.535002
495  6.087610   4.397451
496  3.440847   2.070664
497  4.530545   3.710193

[498 rows x 2 columns]

# 2.데이터 이해

- 분석할 데이터를 **충분히 이해**할 수 있도록 다양한 **탐색** 과정을 수행합니다.

In [3]:
# 상위 몇 개 행 확인
df.head()

     income  happiness
0  3.862647   2.314489
1  4.979381   3.433490
2  4.923957   4.599373
3  3.214372   2.791114
4  7.196409   5.596398

**데이터 설명**

- income: 수입 (단위: 10,000$)
- happiness: 행복 정도 (1~ 10)

In [4]:
# 하위 몇 개 행 확인
df.tail()

       income  happiness
493  5.249209   4.568705
494  3.471799   2.535002
495  6.087610   4.397451
496  3.440847   2.070664
497  4.530545   3.710193

In [5]:
# 변수 확인
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 498 entries, 0 to 497
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   income     498 non-null    float64
 1   happiness  498 non-null    float64
dtypes: float64(2)
memory usage: 7.9 KB

In [6]:
# 데이터 크기 확인
df.shape

(498, 2)

In [7]:
# 기술통계 확인
df.describe()

           income   happiness
count  498.000000  498.000000
mean     4.466902    3.392859
std      1.737527    1.432813
min      1.506275    0.266044
25%      3.006256    2.265864
50%      4.423710    3.472536
75%      5.991913    4.502621
max      7.481521    6.863388

In [8]:
# 상관관계 확인
df.corr()

             income  happiness
income     1.000000   0.865634
happiness  0.865634   1.000000

# 3.데이터 전처리

- **전처리** 과정을 통해 머신러닝 알고리즘에 사용할 수 있는 형태의 데이터를 준비합니다.

**1) x, y 분리**

- 우선 target 변수를 명확히 지정합니다.
- target을 제외한 나머지 변수들 데이터는 x로 선언합니다.
- target 변수 데이터는 y로 선언합니다.
- 이 결과로 만들어진 x는 데이터프레임, y는 시리즈가 됩니다.
- 이후 모든 작업은 x, y를 대상으로 진행합니다.

In [9]:
df.isna().sum()

income       0
happiness    0
dtype: int64

In [10]:
# target 확인

target = 'happiness'

# 데이터 분리
X = df.drop(target, axis=1)
y = df[target]
#  y = df.loc[:, target]

**2) 학습용, 평가용 데이터 분리**

- 학습용, 평가용 데이터를 적절한 비율로 분리합니다.
- 반복 실행 시 동일한 결과를 얻기 위해 random_state 옵션을 지정합니다.

In [11]:
# 모듈 불러오기
from sklearn.model_selection import train_test_split

# 7:3으로 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.7, random_state=1)

# 4.모델링

- 본격적으로 모델을 **선언**하고 **학습**하고 **평가**하는 과정을 진행합니다.
- 우선 **회귀** 문제인지 **분류** 문제인지 명확히 구분합니다.

- 회귀 문제 인가요? 분류 문제인가요?
- 회귀인지 분류인지에 따라 사용할 알고리즘과 평가 방법이 달라집니다.
- 다음 알고리즘 사용
    - 알고리즘: LinearRegression

In [12]:
# 1단계: 불러오기
from sklearn.linear_model import LinearRegression

In [13]:
# 2단계: 선언하기
model = LinearRegression()

In [14]:
# 3단계: 학습하기
model.fit(X_train, y_train)

LinearRegression()

In [15]:
# 4단계: 예측하기
y_pred = model.predict(X_test)
y_pred

array([1.47675337, 4.7089767 , 2.97100026, 1.69215556, 4.84678918,
       3.83806216, 3.51744949, 3.24235528, 4.69334891, 1.51425987,
       1.38157737, 4.13645747, 4.79677245, 2.88518536, 3.56271045,
       4.28468051, 3.95931222, 1.27040806, 1.49663986, 4.99152378,
       5.3740647 , 1.89943231, 1.90944298, 4.61540539, 4.0388369 ,
       1.65980488, 1.6530011 , 2.24848654, 5.11598764, 4.77917612,
       1.30309807, 3.21392181, 2.04380202, 3.44445686, 4.79600505,
       4.8915454 , 5.38155482, 4.12185193, 2.23333945, 2.10030452,
       4.28302034, 1.49137879, 1.36921888, 4.00098604, 2.03957139,
       3.05830637, 3.61026902, 4.71441672, 2.89974849, 5.07017104,
       1.29246255, 2.85980137, 4.11588807, 5.25724692, 2.45574967,
       2.40350015, 4.27257063, 1.88399344, 4.4914489 , 1.47395239,
       4.92924213, 3.55707741, 4.15222488, 5.24188489, 2.27500895,
       2.69200581, 3.73455597, 1.55158499, 5.11594052, 3.76630306,
       1.87168073, 4.16932865, 2.00143459, 4.24551377, 3.48671485,
       1.85267876, 3.9569143 , 5.35643278, 4.92065806, 5.16371067,
       1.90200037, 2.03921946, 5.38930204, 5.01149902, 3.85342045,
       4.68264375, 3.87737381, 3.18181998, 2.44110463, 4.5653437 ,
       1.50416857, 3.36219917, 3.54711029, 1.33932723, 2.1640613 ,
       1.62478922, 1.80579243, 2.87095265, 1.81004379, 2.40537127,
       5.18538138, 2.94204664, 5.38055684, 4.07120713, 5.4047271 ,
       4.90853831, 4.83857093, 4.90479636, 2.80272871, 1.30145457,
       3.40822512, 4.97387522, 5.20285665, 3.96514546, 3.92137171,
       4.54937965, 3.60614883, 3.82879238, 4.51456588, 1.82510282,
       3.0435057 , 3.67571352, 3.258833  , 5.45525074, 2.74453044,
       2.67224291, 3.36714314, 2.20235766, 3.92652808, 3.26885219,
       1.73975443, 2.42132902, 4.46135262, 4.49952629, 1.70519821,
       5.11920671, 4.33301916, 2.68082671, 1.54407966, 4.3369095 ,
       5.36699967, 2.52933357, 1.29574801, 3.84276608, 4.45245103,
       2.95513002, 4.46200947, 2.89018642, 2.723852  , 5.57813245,
       3.54396439, 4.01560343, 1.56999238, 2.09899635, 1.54926893,
       2.15718066, 2.27282876, 5.5581974 , 4.48513226, 4.85725068,
       2.21954749, 1.97805208, 5.26200373, 3.18487194, 2.88964505,
       5.29803368, 2.70749065, 2.06871243, 1.87906743, 1.81336083,
       1.24823585, 4.92063529, 2.23060819, 1.87313672, 5.12776651,
       4.53354111, 3.08838749, 3.22441127, 4.65537933, 3.5725492 ,
       1.81251845, 3.33427497, 4.47636286, 2.59644207, 2.95454548,
       2.15253887, 4.30124782, 5.32559484, 3.96439386, 4.78578372,
       1.42856392, 3.44238391, 5.5036169 , 1.99378234, 5.12297703,
       4.97217651, 2.32652194, 2.44533255, 2.30431491, 4.39867212,
       1.76196827, 3.66340829, 5.33816545, 2.49922442, 5.3702785 ,
       2.72210129, 1.74340336, 2.87322186, 2.77622342, 2.41558469,
       1.68729145, 4.51259138, 4.68901314, 5.323952  , 3.36027419,
       2.71790061, 4.05325503, 3.4973981 , 3.52193982, 1.59748035,
       1.85972418, 2.05958214, 2.95654951, 5.54698433, 2.64406762,
       3.7769939 , 5.32561432, 5.56464875, 2.60830235, 3.49611304,
       3.78757384, 4.58515604, 4.78494837, 4.70568451, 3.19515761,
       2.70164352, 2.64525705, 2.5350307 , 2.74680104, 2.71482992,
       5.13659669, 2.05880823, 2.98207462, 4.28966405, 4.30994948,
       2.69978586, 4.7920134 , 2.36114184, 4.57500501, 4.06013523,
       3.35929584, 2.37637697, 3.84399502, 5.10948067, 2.62045026,
       2.26223813, 5.58894769, 3.25288766, 1.80133506, 3.12008144,
       2.78898086, 5.02283903, 1.53581368, 2.35613546, 4.87590834,
       1.97099967, 4.13510687, 5.45756422, 3.28617213, 2.64972839,
       4.76250179, 2.72222   , 5.02672114, 3.14486325, 2.90329005,
       4.04682928, 3.85048465, 2.1936822 , 2.40005928, 3.89857932,
       4.02934032, 5.07979312, 2.69158308, 2.41752783, 2.757513  ,
       1.69962815, 4.50735071, 4.26901463, 5.28436063, 1.87843274,
       2.26190008, 4.64431944, 4.88241428, 4.41925524, 1.31070551,
       5.4181766 , 5.31260405, 2.55786344, 4.87196582, 5.11246377,
       3.9469577 , 4.63252228, 3.43270877, 2.13321187, 1.65297239,
       3.23385576, 4.04480165, 1.85455546, 1.54645896, 5.57584593,
       1.44769602, 1.26035047, 2.71335629, 5.35046891, 3.17253804,
       1.66736906, 2.46447861, 3.94913699, 4.86160913, 1.59041623,
       3.0971997 , 5.49127434, 2.60776909, 4.32545313, 2.64704996,
       4.08578183, 3.61806291, 3.21907557, 3.48532069, 4.53252746,
       1.31912402, 4.44615604, 4.57613459, 1.52186752, 1.9976076 ,
       4.26711883, 5.15091102, 2.22609847, 3.73702136, 4.29192813,
       3.57353708, 4.77672204, 3.08131796, 1.29348973, 2.10648203,
       2.81669041, 2.80658602, 3.26018999, 2.49009631])

# 5.회귀 성능 평가

- 다양한 성능 지표로 회귀 모델 성능을 평가합니다.

**1) MAE(Mean Absolute Error)**

In [16]:
# 모듈 불러오기
from sklearn.metrics import mean_absolute_error

# 성능 평가
mean_absolute_error(y_test, y_pred)

0.5739221661673545

**2) MSE(Mean Squared Error)**

In [17]:
# 모듈 불러오기
from sklearn.metrics import mean_squared_error

# 성능 평가
mean_squared_error(y_test, y_pred)

0.5140692645601798

**3) RMSE(Root Mean Squared Error)**

In [18]:
# 모듈 불러오기
from sklearn.metrics import root_mean_squared_error

# 성능 평가
root_mean_squared_error(y_test, y_pred)

0.7169862373575798

**4) MAPE(Mean Absolute Percentage Error)**

In [19]:
# 모듈 불러오기
from sklearn.metrics import mean_absolute_percentage_error

# 성능 평가
mean_absolute_percentage_error(y_test, y_pred)

0.25766602188765086

**5) R2-Score**

In [20]:
# 모듈 불러오기
from sklearn.metrics import r2_score

# 성능 평가
r2_score(y_test, y_pred)

0.7482268419397229